/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CadastrarEventoRouteImport } from './routes/cadastrar-evento'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminImportarRouteImport } from './routes/admin/importar'
import { Route as CategoriaIdRouteImport } from './routes/categoria.$id'
import { Route as EventoIdRouteImport } from './routes/evento.$id'
import { Route as AdminEventoIdRouteImport } from './routes/admin/evento/$id'
import { Route as AdminEventoNovoRouteImport } from './routes/admin/evento/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarEventoRoute = CadastrarEventoRouteImport.update({
  id: '/cadastrar-evento',
  path: '/cadastrar-evento',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportarRoute = AdminImportarRouteImport.update({
  id: '/admin/importar',
  path: '/admin/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaIdRoute = CategoriaIdRouteImport.update({
  id: '/categoria/$id',
  path: '/categoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoIdRoute = EventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventoIdRoute = AdminEventoIdRouteImport.update({
  id: '/admin/evento/$id',
  path: '/admin/evento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventoNovoRoute = AdminEventoNovoRouteImport.update({
  id: '/admin/evento/novo',
  path: '/admin/evento/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastrar-evento': typeof CadastrarEventoRoute
  '/favoritos': typeof FavoritosRoute
  '/offline': typeof OfflineRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/admin/importar': typeof AdminImportarRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/evento/$id': typeof EventoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/evento/$id': typeof AdminEventoIdRoute
  '/admin/evento/novo': typeof AdminEventoNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastrar-evento': typeof CadastrarEventoRoute
  '/favoritos': typeof FavoritosRoute
  '/offline': typeof OfflineRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/admin/importar': typeof AdminImportarRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/evento/$id': typeof EventoIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/evento/$id': typeof AdminEventoIdRoute
  '/admin/evento/novo': typeof AdminEventoNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastrar-evento': typeof CadastrarEventoRoute
  '/favoritos': typeof FavoritosRoute
  '/offline': typeof OfflineRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/admin/importar': typeof AdminImportarRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/evento/$id': typeof EventoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/evento/$id': typeof AdminEventoIdRoute
  '/admin/evento/novo': typeof AdminEventoNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/cadastrar-evento'
    | '/favoritos'
    | '/offline'
    | '/perfil'
    | '/sobre'
    | '/admin/importar'
    | '/categoria/$id'
    | '/evento/$id'
    | '/admin/'
    | '/admin/evento/$id'
    | '/admin/evento/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/cadastrar-evento'
    | '/favoritos'
    | '/offline'
    | '/perfil'
    | '/sobre'
    | '/admin/importar'
    | '/categoria/$id'
    | '/evento/$id'
    | '/admin'
    | '/admin/evento/$id'
    | '/admin/evento/novo'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/cadastrar-evento'
    | '/favoritos'
    | '/offline'
    | '/perfil'
    | '/sobre'
    | '/admin/importar'
    | '/categoria/$id'
    | '/evento/$id'
    | '/admin/'
    | '/admin/evento/$id'
    | '/admin/evento/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  CadastrarEventoRoute: typeof CadastrarEventoRoute
  FavoritosRoute: typeof FavoritosRoute
  OfflineRoute: typeof OfflineRoute
  PerfilRoute: typeof PerfilRoute
  SobreRoute: typeof SobreRoute
  AdminImportarRoute: typeof AdminImportarRoute
  CategoriaIdRoute: typeof CategoriaIdRoute
  EventoIdRoute: typeof EventoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventoIdRoute: typeof AdminEventoIdRoute
  AdminEventoNovoRoute: typeof AdminEventoNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-evento': {
      id: '/cadastrar-evento'
      path: '/cadastrar-evento'
      fullPath: '/cadastrar-evento'
      preLoaderRoute: typeof CadastrarEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/importar': {
      id: '/admin/importar'
      path: '/admin/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AdminImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$id': {
      id: '/categoria/$id'
      path: '/categoria/$id'
      fullPath: '/categoria/$id'
      preLoaderRoute: typeof CategoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$id': {
      id: '/evento/$id'
      path: '/evento/$id'
      fullPath: '/evento/$id'
      preLoaderRoute: typeof EventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evento/$id': {
      id: '/admin/evento/$id'
      path: '/admin/evento/$id'
      fullPath: '/admin/evento/$id'
      preLoaderRoute: typeof AdminEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evento/novo': {
      id: '/admin/evento/novo'
      path: '/admin/evento/novo'
      fullPath: '/admin/evento/novo'
      preLoaderRoute: typeof AdminEventoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  CadastrarEventoRoute: CadastrarEventoRoute,
  FavoritosRoute: FavoritosRoute,
  OfflineRoute: OfflineRoute,
  PerfilRoute: PerfilRoute,
  SobreRoute: SobreRoute,
  AdminImportarRoute: AdminImportarRoute,
  CategoriaIdRoute: CategoriaIdRoute,
  EventoIdRoute: EventoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventoIdRoute: AdminEventoIdRoute,
  AdminEventoNovoRoute: AdminEventoNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
