-- Schema do Poa na Rua.
--
-- Rode no SQL editor do Supabase (ou pelo Lovable Cloud) para sair do
-- localStorage e passar a ter dados compartilhados entre todo mundo.
--
-- O formato espelha `src/data/types.ts`, que por sua vez veio do payload da
-- API original do app — assim o site não precisa mudar de formato de dado.

create type event_status as enum ('pending', 'published', 'hidden', 'rejected');

create table categories (
  id          bigint generated by default as identity primary key,
  name        text    not null,
  "order"     int     not null default 0,
  image_url   text,
  created_at  timestamptz not null default now()
);

create table tags (
  id    bigint generated by default as identity primary key,
  name  text not null unique
);

create table events (
  id            bigint generated by default as identity primary key,
  name          text        not null,
  description   text        not null default '',
  address       text        not null default '',
  starts_at     timestamptz not null,
  ends_at       timestamptz,
  hour          text        not null default '',
  image_url     text,
  banner        text,
  featured      boolean     not null default false,
  prioritized   boolean     not null default false,
  latitude      numeric(10, 7),
  longitude     numeric(10, 7),

  status        event_status not null default 'pending',

  -- Procedência: de onde veio e como reencontrar o original.
  source_id     text,
  source_name   text,
  source_url    text,
  external_id   text,
  imported_at   timestamptz,

  -- Chave de deduplicação gerada pelo coletor (nome enxuto + dia).
  dedupe_key    text unique,

  -- Dono, quando o evento foi cadastrado por uma pessoa e não pelo coletor.
  created_by    uuid references auth.users (id) on delete set null,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index events_status_starts_at_idx on events (status, starts_at desc);
create index events_source_idx on events (source_id);

create table event_categories (
  event_id    bigint not null references events (id) on delete cascade,
  category_id bigint not null references categories (id) on delete cascade,
  primary key (event_id, category_id)
);

create table event_tags (
  event_id bigint not null references events (id) on delete cascade,
  tag_id   bigint not null references tags (id) on delete cascade,
  primary key (event_id, tag_id)
);

create table event_contacts (
  id       bigint generated by default as identity primary key,
  event_id bigint not null references events (id) on delete cascade,
  type     text   not null check (type in ('site', 'facebook', 'instagram', 'whatsapp')),
  value    text   not null
);

create table event_favorites (
  user_id  uuid   not null references auth.users (id) on delete cascade,
  event_id bigint not null references events (id) on delete cascade,
  primary key (user_id, event_id)
);

create table event_attendances (
  user_id  uuid   not null references auth.users (id) on delete cascade,
  event_id bigint not null references events (id) on delete cascade,
  primary key (user_id, event_id)
);

create table event_evaluations (
  id         bigint generated by default as identity primary key,
  event_id   bigint not null references events (id) on delete cascade,
  user_id    uuid   not null references auth.users (id) on delete cascade,
  note       int    not null check (note between 1 and 5),
  comment    text   not null default '',
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);

-- Quem pode administrar. Simples de propósito: uma linha por admin.
create table admins (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (select 1 from admins where user_id = auth.uid());
$$;

/* ------------------------------------------------------------------ RLS ---
 * Regra geral: o público lê só evento publicado; escrever é do admin.
 * Favorito, presença e opinião são de cada pessoa.
 */

alter table events            enable row level security;
alter table categories        enable row level security;
alter table tags              enable row level security;
alter table event_categories  enable row level security;
alter table event_tags        enable row level security;
alter table event_contacts    enable row level security;
alter table event_favorites   enable row level security;
alter table event_attendances enable row level security;
alter table event_evaluations enable row level security;
alter table admins            enable row level security;

create policy "evento publicado é público" on events
  for select using (status = 'published' or is_admin());

create policy "admin escreve evento" on events
  for all using (is_admin()) with check (is_admin());

create policy "catálogo é público" on categories for select using (true);
create policy "admin escreve categoria" on categories
  for all using (is_admin()) with check (is_admin());

create policy "tags são públicas" on tags for select using (true);
create policy "admin escreve tag" on tags
  for all using (is_admin()) with check (is_admin());

create policy "relações são públicas" on event_categories for select using (true);
create policy "admin escreve relação de categoria" on event_categories
  for all using (is_admin()) with check (is_admin());

create policy "tags do evento são públicas" on event_tags for select using (true);
create policy "admin escreve tag do evento" on event_tags
  for all using (is_admin()) with check (is_admin());

create policy "contatos são públicos" on event_contacts for select using (true);
create policy "admin escreve contato" on event_contacts
  for all using (is_admin()) with check (is_admin());

create policy "cada um vê seus favoritos" on event_favorites
  for select using (auth.uid() = user_id);
create policy "cada um gerencia seus favoritos" on event_favorites
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "presenças são públicas" on event_attendances for select using (true);
create policy "cada um marca a própria presença" on event_attendances
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "opiniões são públicas" on event_evaluations for select using (true);
create policy "cada um escreve a própria opinião" on event_evaluations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "admin se enxerga" on admins
  for select using (auth.uid() = user_id or is_admin());

/* --------------------------------------------------------------- gatilhos */

create or replace function touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger events_touch_updated_at
  before update on events
  for each row execute function touch_updated_at();

/* ----------------------------------------------------------- catálogo base */

insert into categories (id, name, "order") values
  (47, 'PARA CRIANÇAS', 1),
  (22, 'FEIRAS ORGÂNICAS E ECOLÓGICAS', 2),
  (45, 'ARTESANATO E BRECHÓ', 3),
  (40, 'EVENTOS DE RUA', 4),
  (41, 'MÚSICA E SHOWS', 5),
  (42, 'GASTRONOMIA', 6),
  (46, 'PONTOS TURÍSTICOS', 7),
  (43, 'PARQUES E PRAÇAS', 8),
  (44, 'ARTE E CULTURA', 9);

insert into tags (name) values
  ('FEIRA DE RUA'), ('FESTAS'), ('SHOW'), ('RESTAURANTE'),
  ('AO AR LIVRE'), ('GRATUITO'), ('PET FRIENDLY'), ('PARA CRIANÇAS');

-- Depois de criar tua conta pelo site, vira admin com:
--   insert into admins (user_id) values ('<teu uuid em auth.users>');
